version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
  pre_build:
    commands:
     
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
      - rm -rf ./__tests__
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production
  build:
    commands:
# Discover and run unit tests in the '__tests__' directory
      - npm run test
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket ${BUCKET} --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml

reports:
  jest_reports:
    files: #Store all of the files
      - '**/*'
    file-format: JunitXml
    base-directory: reports